---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    config_ovs_bridges: true
    config_ovs_interfaces: true
    dns_nameservers:
      - 213.133.100.100
      - 213.133.98.98
      - 213.133.99.99
    ovs_bridges:
      - name: br0
        comment: Bridge OVS
        configure : true
        enable: false
        method: manual
        ports:
          - '{{ ansible_default_ipv4.interface }}'
          - mgmt0
#          - xgestio
    ovs_interfaces:
      - name: '{{ ansible_default_ipv4.interface }}'
        comment: Interface fisica
        bridge: br0
        configure : true
        enable: false
        method: manual 
      - name: mgmt0
        address: '{{ ansible_default_ipv4.address }}'
        bridge: br0
        comment: Interface virtual principal
        configure: true
        enable: false
        gateway: '{{ ansible_default_ipv4.gateway }}'
        method: static
        netmask: '{{ ansible_default_ipv4.netmask }}'
        parameters :
          - param: hwaddress ether
            val: '{{ ansible_default_ipv4.macaddress }}'
          - param: mtu
            val: 1500
#      - name: xgestio
#        address: '{{ vgestio_host }}'
#        bridge: br0
#        comment: Interface vlan-gestio
#        configure: true
#        enable: false
#        method: static
#        netmask: 255.255.0.0
#        options:
#          - opt: tag
#            val: 4000
  roles:
    - role: mrlesmithjr.config-interfaces
#    - role: mrlesmithjr.ansible-openvswitch
#    - role: mrlesmithjr.netplan
#      netplan_enabled: true
#      netplan_apply: false
#      netplan_config_file: /etc/netplan/01-netcfg.yaml
#      netplan_renderer: networkd
#      netplan_configuration:
#        network:
#          version: 2
#          ethernets:
  tasks:
#    - name: Reiniciar per aplicar els canvis de xarxa
#      shell: sleep 10 && /sbin/shutdown -r now 'Reiniciar per aplicar els canvis de xarxa' 
#      async: 300
#      poll: 0
#      ignore_errors: true
#    - name: Esperar a que el servidor torni a estar disponible
#      wait_for_connection:
#        delay: 60
#        timeout: 300
    - name: Verificar Switch
      command: ovs-vsctl show
      register: ovs_result
    - name: Veure OVS Bridge
      debug:
        var: ovs_result.stdout_lines
