---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    bridge_pri: br0
  roles:
    - role: mrlesmithjr.config-interfaces
      config_network_interfaces: true
      config_ovs_bridges: true
      config_ovs_interfaces: true
      pri_domain_name: lonuvol.local
      dns_nameservers:
        - 213.133.100.100
        - 213.133.98.98
        - 213.133.99.99
      network_interfaces:
        - name: '{{ ansible_default_ipv4.interface }}'
          configure : true
          enable: false
          method: manual
      ovs_bridges:
        - name: '{{ bridge_pri }}'
          comment: Bridge OVS
          configure : true
          enable: false
          method: manual
          ports:
            - '{{ ansible_default_ipv4.interface }}'
            - mgmt0
            - vlan4000
      ovs_interfaces:
        - name: mgmt0
          address: '{{ ansible_default_ipv4.address }}'
          bridge: '{{ bridge_pri }}'
          comment: Interface virtual principal
          configure: true
          enable: false
          gateway: '{{ ansible_default_ipv4.gateway }}'
          method: static
          netmask: '{{ ansible_default_ipv4.netmask }}'
          parameters :
            - param: hwaddress ether
              val: '{{ ansible_default_ipv4.macaddress }}'
            - param: mtu
              val: 1500
        - name: vlan4000
          address: '{{ vgestio_host }}'
          bridge: '{{ bridge_pri }}'
          comment: Interface vlan-gestio
          configure: true
          enable: false
          method: static
          netmask: 255.255.255.0
          options:
            - opt: tag
              val: 4000
    - role: mrlesmithjr.ansible-openvswitch
    - role: mrlesmithjr.netplan
      netplan_enabled: true
      netplan_apply: false
      netplan_config_file: /etc/netplan/01-netcfg.yaml
      netplan_renderer: networkd
      netplan_configuration:
        network:
          version: 2
          ethernets:
  tasks:
    - name: Aplicar canvis
      shell: ifdown --all && ifup --all && ovs-vsctl add-port '{{ bridge_pri }}' '{{ ansible_default_ipv4.interface }}'
      ignore_errors: yes
    - name: Verificar Switch
      command: ovs-vsctl show
      register: ovs_result
    - name: Veure OVS Bridge
      debug:
        var: ovs_result.stdout_lines
