---
- hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars/default.yml
  
  tasks:
    - name: Fes un update apt
      apt: update_cache=yes force_apt_get=yes autoremove=yes cache_valid_time=3600
      
    - name: Instalar paquets basics
      apt: name={{ sys_packages }} state=latest
    
    - name: Instalar paquets amb versio especifica
      apt: name='{{ item.name }}'
      with_items: "{{ lock_packages }}"
    
    - name: Bloquejar paquets
      dpkg_selections: name={{ item.name }} selection=hold
      with_items: "{{ lock_packages }}"
      
    - name: Configurar Interfaces
      include_role:
        name: ansible-config-interfaces
      vars:
        config_network_interfaces: true
        config_ovs_bridges: true
        config_ovs_interfaces: true
        network_interfaces:
          - name: '{{ ansible_default_ipv4.interface }}'
            bridge: '{{ bridge_pri }}'
            configure : true
            enable: false
            method: manual
        ovs_bridges:
          - name: '{{ bridge_pri }}'
            comment: Bridge OVS
            configure : true
            enable: false
            method: manual
            ports:
              - '{{ bridge_pri  }}'

        ovs_interfaces:
          - name: mgmt0
            address: '{{ ansible_default_ipv4.address }}'
            bridge: '{{ bridge_pri }}'
            comment: Interface virtual principal
            configure: true
            enable: false
            gateway: '{{ ansible_default_ipv4.gateway }}'
            method: static
            netmask: '{{ ansible_default_ipv4.netmask }}'
            parameters :
              - param: hwaddress ether
                val: '{{ ansible_default_ipv4.macaddress }}'
              - param: post-up
                val: ovs-vsctl add-port {{ bridge_pri }} {{ ansible_default_ipv4.interface }}
          - name: vswitch1
            address: '{{ vgestio_host }}'
            bridge: '{{ bridge_pri }}'
            comment: Interface vswitch1
            configure: true
            enable: false
            method: static
            netmask: 255.255.0.0
            parameters :
              - param: mtu
                val: 1400
            options:
              - opt: tag
                val: 4001
      when: 
        - "'nous' in group_names"

    - name: Configurar DNS
      include_role:
        name: oefenweb.dns
      vars:
        dns_domain: '{{ pri_domain_name }}'
 
    - name: Reiniciar DNS
      systemd:
        name: systemd-resolved
        state: restarted
                
    - name: Deshabilitar netplan
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - systemd-networkd
        - systemd-networkd.socket
          
    - name: Desinstal·lar Netplan
      apt:
        name: netplan.io
        state: absent

    - name: Aplicar canvis
      shell: ip addr flush dev {{ ansible_default_ipv4.interface }} && ifdown --all && ifup --all
      ignore_errors: yes
      when: 
        - "'nous' in group_names"

    - name: Verificar Switch
      command: ovs-vsctl show
      register: ovs_result
      
    - name: Veure OVS Bridge
      debug:
        var: ovs_result.stdout_lines
