---
- hosts: all
  gather_facts: yes
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]
    - debug: var=inventory_hostname
    - debug: var=awx_inventory_name
    - debug: var=ansible_default_ipv4.interface
    - debug: var=vlan-gestio_host
    - debug: var=ansible_facts
